Repository jupyter/nbconvert, pull requests merged in 2021-12, with the labels that each got.

#1692 Fix typos in execute.py
  nbconvert/preprocessors/execute.py
Labels: documentation

#1687 Modernize latex greek math handling (partially fixes #1673)
  share/jupyter/nbconvert/templates/latex/base.tex.j2
Labels: enhancement

#1696 Fix use of deprecated API and update test matrix
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  nbconvert/preprocessors/tests/test_svg2pdf.py
  nbconvert/tests/test_nbconvertapp.py
  nbconvert/utils/version.py
Labels: maintenance

#1695 Update nbconvert_library.ipynb
  docs/source/nbconvert_library.ipynb
Labels: documentation
