Repository jupyter/nbconvert, pull requests merged in 2022-08, with the labels that each got.

#1818 Bump minimum version of mistune
  pyproject.toml
Labels: maintenance

#1828 Fix linters
  nbconvert/exporters/templateexporter.py
Labels: maintenance

#1829 escape_html: prevent escaping quotes
  nbconvert/exporters/templateexporter.py
  share/jupyter/nbconvert/templates/classic/base.html.j2
  share/jupyter/nbconvert/templates/lab/base.html.j2
Labels: bug

#1830 escape_html: prevent escaping quotes on widgets JSON reprs (#1829)
  nbconvert/exporters/templateexporter.py
  share/templates/classic/base.html.j2
  share/templates/lab/base.html.j2
Labels: bug

#1832 Fix title
  share/templates/classic/index.html.j2
  share/templates/lab/index.html.j2
  share/templates/reveal/index.html.j2
Labels: bug

#1833 Backport: Fix title
  share/jupyter/nbconvert/templates/classic/index.html.j2
  share/jupyter/nbconvert/templates/lab/index.html.j2
  share/jupyter/nbconvert/templates/reveal/index.html.j2
Labels: bug

#1841 Handle nbformat 5.5
  nbconvert/exporters/exporter.py
  nbconvert/exporters/tests/files/notebook_inject.ipynb
  nbconvert/exporters/tests/test_exporter.py
  nbconvert/preprocessors/tagremove.py
  share/templates/base/null.j2
  share/templates/latex/null.j2
Labels: maintenance

#1845 Update Changelog for 7.0
  docs/source/changelog.rst
Labels: documentation
