Repository jupyter/nbconvert, pull requests merged in 2023-12, with the labels that each got.

#2079 Update ruff config
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  docs/autogen_config.py
  docs/source/conf.py
  hatch_build.py
  nbconvert/_version.py
  nbconvert/exporters/base.py
  nbconvert/exporters/exporter.py
  nbconvert/exporters/html.py
  nbconvert/exporters/pdf.py
  nbconvert/exporters/qt_exporter.py
  nbconvert/exporters/qtpdf.py
  nbconvert/exporters/qtpng.py
  nbconvert/exporters/script.py
  nbconvert/exporters/templateexporter.py
  nbconvert/exporters/webpdf.py
  nbconvert/filters/ansi.py
  nbconvert/filters/citation.py
  nbconvert/filters/filter_links.py
  nbconvert/filters/highlight.py
  nbconvert/filters/markdown_mistune.py
  nbconvert/filters/strings.py
  nbconvert/nbconvertapp.py
  nbconvert/postprocessors/serve.py
  nbconvert/preprocessors/base.py
  nbconvert/preprocessors/clearmetadata.py
  nbconvert/preprocessors/csshtmlheader.py
  nbconvert/preprocessors/execute.py
  nbconvert/preprocessors/extractattachments.py
  nbconvert/preprocessors/extractoutput.py
  nbconvert/preprocessors/highlightmagics.py
  nbconvert/preprocessors/sanitize.py
  nbconvert/preprocessors/svg2pdf.py
  nbconvert/utils/_contextlib_chdir.py
  nbconvert/utils/exceptions.py
  nbconvert/utils/io.py
  nbconvert/utils/lexers.py
  nbconvert/utils/pandoc.py
  nbconvert/utils/text.py
  nbconvert/writers/debug.py
  nbconvert/writers/stdout.py
  pyproject.toml
  tests/base.py
  tests/exporters/test_templateexporter.py
  tests/exporters/test_webpdf.py
  tests/filters/test_citation.py
  tests/filters/test_markdown.py
  tests/test_nbconvertapp.py
  tests/utils/test_io.py
Labels: maintenance

#2084 Remove twitter links that cause linkcheck to fail
  docs/source/nbconvert_library.ipynb
Labels: maintenance

#2083 Add table, td, tr to allowed list of tags
  nbconvert/filters/strings.py
Labels: enhancement

#2086 Restore removed import
  CHANGELOG.md
  nbconvert/preprocessors/execute.py
  pyproject.toml
Labels: bug

#2087 Clean up import
  CHANGELOG.md
  nbconvert/preprocessors/execute.py
Labels: maintenance

#2088 Fix webpdf test on Python 3.12
  nbconvert/exporters/webpdf.py
Labels: maintenance

#2089 Convert `coalescese_streams` function to `CoalesceStreamsPreprocessor`
  docs/source/api/preprocessors.rst
  nbconvert/exporters/exporter.py
  nbconvert/nbconvertapp.py
  nbconvert/preprocessors/__init__.py
  nbconvert/preprocessors/coalescestreams.py
  tests/preprocessors/test_coalescestreams.py
Labels: enhancement
