Repository jupyter/nbconvert, pull requests merged in 2023-10, with the labels that each got.

#2048 Fixup typings
  nbconvert/nbconvertapp.py
  nbconvert/preprocessors/sanitize.py
  pyproject.toml
  tests/exporters/test_qtpng.py
Labels: maintenance

#2051 Update to mermaidjs 10.5.0
  nbconvert/exporters/html.py
  share/templates/lab/mermaidjs.html.j2
Labels: maintenance

#2053 Include tests in sdist
  CHANGELOG.md
  pyproject.toml
Labels: maintenance

#2055 Restore ResourcesDict to the public API
  CHANGELOG.md
  nbconvert/exporters/__init__.py
Labels: bug

#2056 Update typings and remove dead link
  CHANGELOG.md
  README.md
  nbconvert/exporters/base.py
  nbconvert/exporters/qt_screenshot.py
  nbconvert/exporters/script.py
  nbconvert/exporters/webpdf.py
  nbconvert/filters/filter_links.py
  nbconvert/filters/pandoc.py
  nbconvert/filters/strings.py
  nbconvert/preprocessors/csshtmlheader.py
  pyproject.toml
Labels: maintenance

#2058 Update to mermaid 10.6.0, docs keyboard navigation
  docs/source/conf.py
  nbconvert/exporters/html.py
  share/templates/lab/mermaidjs.html.j2
Labels: enhancement, documentation

#2059 Adopt ruff format
  .pre-commit-config.yaml
  nbconvert/exporters/webpdf.py
  nbconvert/filters/markdown_mistune.py
  nbconvert/filters/strings.py
  nbconvert/preprocessors/svg2pdf.py
  nbconvert/preprocessors/tagremove.py
  pyproject.toml
  tests/base.py
  tests/exporters/test_html.py
  tests/exporters/test_webpdf.py
  tests/filters/test_markdown.py
  tests/preprocessors/test_highlightmagics.py
  tests/test_nbconvertapp.py
Labels: maintenance

#2060 Fix typing for traitlets 5.13
  nbconvert/exporters/exporter.py
  nbconvert/exporters/pdf.py
  nbconvert/exporters/templateexporter.py
  nbconvert/nbconvertapp.py
  nbconvert/preprocessors/regexremove.py
  nbconvert/preprocessors/sanitize.py
  nbconvert/writers/base.py
  pyproject.toml
Labels: maintenance

#2062 Remove not needed pytest-dependency test requirement
  CHANGELOG.md
  pyproject.toml
Labels: maintenance
