Repository jupyter/nbconvert, pull requests merged in 2023-07, with the labels that each got.

#2018 html: write image/svg+xml data as base64 and skip clean_html
  nbconvert/filters/strings.py
  nbconvert/filters/svg_constants.py
  nbconvert/tests/files/issue1849_svg.ipynb
  nbconvert/tests/test_nbconvertapp.py
  share/templates/classic/base.html.j2
  share/templates/lab/base.html.j2
Labels: bug

#2021 [Accessibility] some accessibility improvements
  nbconvert/exporters/html.py
  nbconvert/exporters/tests/test_html.py
  nbconvert/tests/test_nbconvertapp.py
  nbconvert/utils/iso639_1.py
  share/templates/classic/index.html.j2
  share/templates/lab/index.html.j2
  share/templates/reveal/index.html.j2
Labels: enhancement

#2008 Support Python 3.8-3.12
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  nbconvert/tests/base.py
  nbconvert/tests/test_nbconvertapp.py
  pyproject.toml
Labels: maintenance

#2013 Adopt playwright
  .github/workflows/tests.yml
  docs/source/install.rst
  docs/source/usage.rst
  nbconvert/exporters/tests/test_webpdf.py
  nbconvert/exporters/webpdf.py
  nbconvert/tests/test_nbconvertapp.py
  pyproject.toml
Labels: enhancement

#1934 Remove HTML escaping JSON-encoded widget state
  nbconvert/exporters/templateexporter.py
  share/templates/classic/base.html.j2
  share/templates/lab/base.html.j2
Labels: bug

#2022 Restore 'media=print' option
  nbconvert/exporters/webpdf.py
Labels: bug

#2024 Show a warning if an image has no alternative text
  nbconvert/exporters/html.py
  nbconvert/exporters/tests/test_html.py
Labels: bug

#2025 Restore pauses during webpdf render
  nbconvert/exporters/webpdf.py
Labels: bug
