Repository jupyter/nbconvert, pull requests merged in 2023-02, with the labels that each got.

#1949 Clean up license (#1949)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
  LICENSE
  README.md
Labels: maintenance

#1897 Add cell-id anchor for cell identification
  share/templates/base/cell_id_anchor.j2
  share/templates/classic/base.html.j2
  share/templates/lab/base.html.j2
Labels: enhancement

#1947 Do not import pyppeteer for installation check (#1947)Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com> Co-authored-by: Matthias Bussonnier <bussonniermatthias@gmail.com>
  nbconvert/exporters/webpdf.py
Labels: bug
