Repository jupyter/nbconvert, pull requests merged in 2023-04, with the labels that each got.

#1963 Make date configurable in latex/PDF
  docs/source/usage.rst
  nbconvert/preprocessors/latex.py
  share/templates/latex/base.tex.j2
Labels: enhancement

#1972 Remove overwriting of default KernelManager
  nbconvert/preprocessors/execute.py
Labels: bug

#1976 Use local coverage
  .github/workflows/tests.yml
  README.md
  codecov.yml
  pyproject.toml
Labels: maintenance

#1984 Ensure toml support in coverage reporting
  pyproject.toml
Labels: maintenance

#1985 Fix test_errors_print_traceback test
  nbconvert/tests/test_nbconvertapp.py
Labels: maintenance
