Repository jupyter/nbconvert, pull requests merged in 2023-06, with the labels that each got.

#1990 exclude bleach 5.0.0 from dependencies resolution
  pyproject.toml
Labels: maintenance

#1997 bump pandoc max version
  .github/workflows/tests.yml
  nbconvert/utils/pandoc.py
  share/templates/latex/base.tex.j2
Labels: maintenance, dependencies

#2002 Ensure TEXINPUTS is an absolute path
  nbconvert/exporters/pdf.py
  nbconvert/exporters/tests/test_pdf.py
Labels: bug

#2005 Fix pdf conversion with explicitly relative paths
  nbconvert/exporters/latex.py
  nbconvert/filters/pandoc.py
  nbconvert/filters/tests/test_pandoc.py
  share/templates/latex/document_contents.tex.j2
Labels: bug, format:LaTeX, format:PDF

#1957 add mermaidjs 10.2.3
  nbconvert/exporters/html.py
  nbconvert/filters/markdown_mistune.py
  nbconvert/filters/tests/test_markdown.py
  share/templates/classic/index.html.j2
  share/templates/lab/index.html.j2
  share/templates/lab/mermaidjs.html.j2
  share/templates/reveal/index.html.j2
Labels: enhancement

#1820 Update to Mistune v3
  nbconvert/filters/markdown.py
  nbconvert/filters/markdown_mistune.py
  pyproject.toml
Labels: maintenance
