Repository jupyter/nbconvert, pull requests merged in 2024-02, with the labels that each got.

#2103 handle xhtml void elements in mermaid diagrams
  CHANGELOG.md
  share/templates/lab/mermaidjs.html.j2
Labels: maintenance

#2106 Add a toggle to skip the svg encoding of images
  CHANGELOG.md
  nbconvert/exporters/html.py
  share/templates/classic/base.html.j2
  share/templates/lab/base.html.j2
Labels: enhancement

#2107 Update project description
  CHANGELOG.md
  pyproject.toml
Labels: documentation

#2108 fix for tests/ dir not in sys.path, closes #2066
  tests/test_nbconvertapp.py
Labels: maintenance

#2111 Update publish workflow
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
Labels: maintenance
