Repository jupyter/nbconvert, pull requests merged in 2025-01, with the labels that each got.

#2199 Add support for mistune 3.1.0
  .github/workflows/tests.yml
  docs/source/nbconvert_library.ipynb
  nbconvert/filters/markdown_mistune.py
Labels: enhancement

#2206 remove any twitter mention
  CHANGELOG.md
  docs/api_examples/template_path/project_templates/nbconvert/templates/classic_clone/static/style.css
Labels: maintenance

#2196 Update base.tex.j2 for macro compatibility with newer versions of Pandoc
  share/templates/latex/base.tex.j2
Labels: maintenance

#2160 Fix crash when running with optimization
  nbconvert/exporters/templateexporter.py
Labels: bug

#2177 Fix bullet list parsing in markdown
  nbconvert/filters/markdown.py
Labels: bug
